### GET latest config
GET http://localhost:8080/configs/latest


### Modify latest config
PUT http://localhost:8080/configs/latest
user-id: pippo

{
  "name": "john",
  "logLevel": "DEBUG",
  "age": 40,
  "friends": ["jack", "doug"]
}

### List config versions
GET http://localhost:8080/configs?fromVersion=0&toVersion=21
